#!/bin/bash

bold="\033[1m"
reset="\033[0m"
green="\033[32m"
red="\033[31m"
yellow="\033[33m"
cyan="\033[36m"

echo -e $bold -- colorados --

echo -e $bold $cyan '\n * PINTOS PHASE - Utility\n * Made by Colorados Team in 2021'

echo -e $reset $green '\n Changing phase...'

if [ -n "$BASH_VERSION" ]; then
SHRC='.bashrc'
else
SHRC='.zshrc'
fi

pintosph=`python <<- EOF
import re
import sys
import os

with open(os.environ['HOME'] + '/%s' % '$SHRC', 'r+') as bfile:

    val = bfile.read()

    phase = '$1'
    val = re.sub(r'PINTOSPH=".*" # stop@000001', 'PINTOSPH="%s" # stop@000001' % phase, val)
    bfile.seek(0)
    bfile.write(val)
    bfile.truncate()
EOF`

PINTOSPH="$1"
echo -e $green " Current phase in active terminal: $PINTOSPH"
export PINTOSPH

echo -e $yellow "\n Errors in writing of $SHRC:\n" $red

if [ -n "$pintosph" ]; then
  echo $pintosph
else
  echo -e $bold $green ' None! :)'
fi
echo -e "\e[0m"

echo -n -e "\e[32m * Matched line in $SHRC:\n\n "
MLINE=`cat ~/$SHRC | grep '# stop@000001'`

if [ -n "$MLINE" ]; then
echo $MLINE
else
echo -e $red "None!! you need to add the follow lines into ~/$SHRC\n"
echo "PINTOSPH=\"\" # stop@000001"
echo "export PINTOSPH
fi

echo -e $yellow '\n bye!\n' $reset

