#!/bin/bash

dockerid="$(dirname $0)"
dockerid="$(dirname $dockerid)"

dockerid=$dockerid/.container-id

if [ ! -f "$dockerid" ]; then
    docker create -t -i -v ~/pintos:/root/pintos \
    -v ~/pintos/.pintos-docker:/root/.pintos-docker --cidfile $dockerid pintos
fi

dockerid=`cat $dockerid`

if [[ -n "$(docker container list --no-trunc -q | grep $dockerid)" ]];
then
    docker exec -it $dockerid bash
else
    docker start -i $dockerid
fi

